---
- name: "Graylog server should be configured"
  template:
    src: "graylog.server.conf.j2"
    dest: "/etc/graylog/server/server.conf"
    owner: "graylog"
    group: "graylog"
    mode: 0644
  notify: "restart graylog-server"

- name: "Graylog server defaults should be configured"
  template:
    src: "graylog.server.default.j2"
    dest: "{{ graylog_server_defaults_file_path }}"
    owner: "graylog"
    group: "graylog"
    mode: 0644
  notify: "restart graylog-server"
