---
- name: Ensure package idependent are installed.
  apt:
    name: "{{ apt_packages_name }}"
    update_cache: true
    state: present
  when: apt_packages_name is defined

- name: Install Graylog repository.
  apt:
    deb: https://packages.graylog2.org/repo/packages/graylog-3.0-repository_latest.deb

- name: Ensure {{ service_name }} are installed.
  apt:
    name: "{{ packages_name }}"
    update_cache: true
    state: present

# - name: "setup-Debian.yml | Set elasticsearch priority to {{ graylog_es_debian_pin_version }} apt_preferences"
#   template:
#     src: "apt_preferences.d/debian_elasticsearch.j2"
#     dest: "/etc/apt/preferences.d/elasticsearch"
#     owner: "root"
#     mode: 0644
