---

- name: "reload systemd configuration"
  systemd:
    daemon_reload: true

- name: "restart graylog-server"
  service:
    name: "graylog-server"
    state: "restarted"
    enabled: true

- name: "restart mongod"
  service:
    name: "mongod"
    state: "restarted"
    enabled: true
